//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xul.Common.Enums
{
    using System;
    
    public enum MaritalStatus : int
    {
        SINGLE = 1,
        MARRIED = 2,
        WIDOW = 3
    }
}
