// <auto-generated />
namespace Xul.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class level0 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(level0));
        
        string IMigrationMetadata.Id
        {
            get { return "201809040628211_level0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
