//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations.Schema;
using System.Web.Mvc;

namespace Xul.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Xml.Linq;

    public partial class Class
    {
        public Class()
        {
            this.Students = new HashSet<Student>();
        }
    
        public int Id { get; set; }
        [DisplayName("Class Name")]
        [Remote("IsClass_Available", "Class", ErrorMessage = "Class already exists !", AdditionalFields = "InitialClassName")]
        public string ClassName { get; set; }
     [ForeignKey("School")]
        public int SchoolId { get; set; }
    
        public virtual ICollection<Student> Students { get; set; }
        public virtual School School { get; set; }
    }
}
