//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Xul.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class School
    {
        public School()
        {
            this.Domitories = new HashSet<Domitory>();
            this.Employees = new HashSet<Employee>();
            this.Classes = new HashSet<Class>();
        }
    [Key]
        public int Id { get; set; }
        [DisplayName("School")]
        public string SchoolName { get; set; }
        [DisplayName("Registration Name")]
        public string RegNo { get; set; }
    
        public virtual ICollection<Domitory> Domitories { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<Class> Classes { get; set; }
    }
}
