//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xul.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    using Xul.Common.Base;

    public partial class Student:StudentItems
    {
        public Student()
        {
            this.Subjects = new HashSet<Subject>();
            this.Attendences = new HashSet<Attendence>();
        }
    
        public int Id { get; set; }
        public string AdmissionNo { get; set; }
        public int SchoolId { get; set; }
        public int ClassId { get; set; }
        public int ParentId { get; set; }
    
        public virtual ICollection<Subject> Subjects { get; set; }
        public virtual Class Class { get; set; }
        public virtual ICollection<Attendence> Attendences { get; set; }
        public virtual Parent Parent { get; set; }
    }
}
